// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_banco_geek.Infraestructure;

namespace api_banco_geek.Infraestructure.Migrations
{
    [DbContext(typeof(ApiBancoGeekDbContext))]
    [Migration("20220215013909_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api_banco_geek.Infraestructure.Entities.ApiCallLog", b =>
                {
                    b.Property<int>("IdApiCallLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResultValueInFibonnaci")
                        .HasColumnType("bit");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ResultValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ValueA")
                        .HasColumnType("int");

                    b.Property<int>("ValueB")
                        .HasColumnType("int");

                    b.HasKey("IdApiCallLog");

                    b.ToTable("ApiCallLog");
                });

            modelBuilder.Entity("api_banco_geek.Infraestructure.Entities.FibonacciValue", b =>
                {
                    b.Property<int>("IdValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdValue");

                    b.ToTable("FibonacciValue");

                    b.HasData(
                        new
                        {
                            IdValue = 1,
                            Value = 0m
                        },
                        new
                        {
                            IdValue = 2,
                            Value = 1m
                        },
                        new
                        {
                            IdValue = 3,
                            Value = 1m
                        },
                        new
                        {
                            IdValue = 4,
                            Value = 2m
                        },
                        new
                        {
                            IdValue = 5,
                            Value = 3m
                        },
                        new
                        {
                            IdValue = 6,
                            Value = 5m
                        },
                        new
                        {
                            IdValue = 7,
                            Value = 8m
                        },
                        new
                        {
                            IdValue = 8,
                            Value = 13m
                        },
                        new
                        {
                            IdValue = 9,
                            Value = 21m
                        },
                        new
                        {
                            IdValue = 10,
                            Value = 34m
                        },
                        new
                        {
                            IdValue = 11,
                            Value = 55m
                        },
                        new
                        {
                            IdValue = 12,
                            Value = 89m
                        },
                        new
                        {
                            IdValue = 13,
                            Value = 144m
                        },
                        new
                        {
                            IdValue = 14,
                            Value = 233m
                        },
                        new
                        {
                            IdValue = 15,
                            Value = 377m
                        },
                        new
                        {
                            IdValue = 16,
                            Value = 610m
                        },
                        new
                        {
                            IdValue = 17,
                            Value = 987m
                        },
                        new
                        {
                            IdValue = 18,
                            Value = 1597m
                        },
                        new
                        {
                            IdValue = 19,
                            Value = 2584m
                        },
                        new
                        {
                            IdValue = 20,
                            Value = 4181m
                        },
                        new
                        {
                            IdValue = 21,
                            Value = 6765m
                        },
                        new
                        {
                            IdValue = 22,
                            Value = 10946m
                        },
                        new
                        {
                            IdValue = 23,
                            Value = 17711m
                        },
                        new
                        {
                            IdValue = 24,
                            Value = 28657m
                        },
                        new
                        {
                            IdValue = 25,
                            Value = 46368m
                        },
                        new
                        {
                            IdValue = 26,
                            Value = 75025m
                        },
                        new
                        {
                            IdValue = 27,
                            Value = 121393m
                        },
                        new
                        {
                            IdValue = 28,
                            Value = 196418m
                        },
                        new
                        {
                            IdValue = 29,
                            Value = 317811m
                        },
                        new
                        {
                            IdValue = 30,
                            Value = 514229m
                        },
                        new
                        {
                            IdValue = 31,
                            Value = 832040m
                        },
                        new
                        {
                            IdValue = 32,
                            Value = 1346269m
                        },
                        new
                        {
                            IdValue = 33,
                            Value = 2178309m
                        },
                        new
                        {
                            IdValue = 34,
                            Value = 3524578m
                        },
                        new
                        {
                            IdValue = 35,
                            Value = 5702887m
                        },
                        new
                        {
                            IdValue = 36,
                            Value = 9227465m
                        },
                        new
                        {
                            IdValue = 37,
                            Value = 14930352m
                        },
                        new
                        {
                            IdValue = 38,
                            Value = 24157817m
                        },
                        new
                        {
                            IdValue = 39,
                            Value = 39088169m
                        },
                        new
                        {
                            IdValue = 40,
                            Value = 63245986m
                        },
                        new
                        {
                            IdValue = 41,
                            Value = 102334155m
                        },
                        new
                        {
                            IdValue = 42,
                            Value = 165580141m
                        },
                        new
                        {
                            IdValue = 43,
                            Value = 267914296m
                        },
                        new
                        {
                            IdValue = 44,
                            Value = 433494437m
                        },
                        new
                        {
                            IdValue = 45,
                            Value = 701408733m
                        },
                        new
                        {
                            IdValue = 46,
                            Value = 1134903170m
                        },
                        new
                        {
                            IdValue = 47,
                            Value = 1836311903m
                        },
                        new
                        {
                            IdValue = 48,
                            Value = 2971215073m
                        },
                        new
                        {
                            IdValue = 49,
                            Value = 4807526976m
                        },
                        new
                        {
                            IdValue = 50,
                            Value = 7778742049m
                        },
                        new
                        {
                            IdValue = 51,
                            Value = 12586269025m
                        },
                        new
                        {
                            IdValue = 52,
                            Value = 20365011074m
                        },
                        new
                        {
                            IdValue = 53,
                            Value = 32951280099m
                        },
                        new
                        {
                            IdValue = 54,
                            Value = 53316291173m
                        },
                        new
                        {
                            IdValue = 55,
                            Value = 86267571272m
                        },
                        new
                        {
                            IdValue = 56,
                            Value = 139583862445m
                        },
                        new
                        {
                            IdValue = 57,
                            Value = 225851433717m
                        },
                        new
                        {
                            IdValue = 58,
                            Value = 365435296162m
                        },
                        new
                        {
                            IdValue = 59,
                            Value = 591286729879m
                        },
                        new
                        {
                            IdValue = 60,
                            Value = 956722026041m
                        },
                        new
                        {
                            IdValue = 61,
                            Value = 1548008755920m
                        },
                        new
                        {
                            IdValue = 62,
                            Value = 2504730781961m
                        },
                        new
                        {
                            IdValue = 63,
                            Value = 4052739537881m
                        },
                        new
                        {
                            IdValue = 64,
                            Value = 6557470319842m
                        },
                        new
                        {
                            IdValue = 65,
                            Value = 10610209857723m
                        },
                        new
                        {
                            IdValue = 66,
                            Value = 17167680177565m
                        },
                        new
                        {
                            IdValue = 67,
                            Value = 27777890035288m
                        },
                        new
                        {
                            IdValue = 68,
                            Value = 44945570212853m
                        },
                        new
                        {
                            IdValue = 69,
                            Value = 72723460248141m
                        },
                        new
                        {
                            IdValue = 70,
                            Value = 117669030460994m
                        },
                        new
                        {
                            IdValue = 71,
                            Value = 190392490709135m
                        },
                        new
                        {
                            IdValue = 72,
                            Value = 308061521170129m
                        },
                        new
                        {
                            IdValue = 73,
                            Value = 498454011879264m
                        },
                        new
                        {
                            IdValue = 74,
                            Value = 806515533049393m
                        },
                        new
                        {
                            IdValue = 75,
                            Value = 1304969544928657m
                        },
                        new
                        {
                            IdValue = 76,
                            Value = 2111485077978050m
                        },
                        new
                        {
                            IdValue = 77,
                            Value = 3416454622906707m
                        },
                        new
                        {
                            IdValue = 78,
                            Value = 5527939700884757m
                        },
                        new
                        {
                            IdValue = 79,
                            Value = 8944394323791464m
                        },
                        new
                        {
                            IdValue = 80,
                            Value = 14472334024676221m
                        },
                        new
                        {
                            IdValue = 81,
                            Value = 23416728348467685m
                        },
                        new
                        {
                            IdValue = 82,
                            Value = 37889062373143906m
                        },
                        new
                        {
                            IdValue = 83,
                            Value = 61305790721611591m
                        },
                        new
                        {
                            IdValue = 84,
                            Value = 99194853094755497m
                        },
                        new
                        {
                            IdValue = 85,
                            Value = 160500643816367088m
                        },
                        new
                        {
                            IdValue = 86,
                            Value = 259695496911122585m
                        },
                        new
                        {
                            IdValue = 87,
                            Value = 420196140727489673m
                        },
                        new
                        {
                            IdValue = 88,
                            Value = 679891637638612258m
                        },
                        new
                        {
                            IdValue = 89,
                            Value = 1100087778366101931m
                        },
                        new
                        {
                            IdValue = 90,
                            Value = 1779979416004714189m
                        },
                        new
                        {
                            IdValue = 91,
                            Value = 2880067194370816120m
                        },
                        new
                        {
                            IdValue = 92,
                            Value = 4660046610375530309m
                        },
                        new
                        {
                            IdValue = 93,
                            Value = 7540113804746346429m
                        },
                        new
                        {
                            IdValue = 94,
                            Value = 12200160415121876738m
                        },
                        new
                        {
                            IdValue = 95,
                            Value = 19740274219868223167m
                        },
                        new
                        {
                            IdValue = 96,
                            Value = 31940434634990099905m
                        },
                        new
                        {
                            IdValue = 97,
                            Value = 51680708854858323072m
                        },
                        new
                        {
                            IdValue = 98,
                            Value = 83621143489848422977m
                        },
                        new
                        {
                            IdValue = 99,
                            Value = 135301852344706746049m
                        },
                        new
                        {
                            IdValue = 100,
                            Value = 218922995834555169026m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
